site_name: napari-particles
site_description: A particle layer for napari
site_author: Martin Weigert

theme: readthedocs


repo_url: https://github.com/maweigert/napari-particles

pages:
- Home: index.md
